### ISSUE TITLE
[Feature Request] iOS-Release target (strip debug symbols and stuff)

### ISSUE THREAD

**Issue by MrGcGamer** [DragonBuild/dragon#83]

**Comment by vr1s** [comment]
https://github.com/DragonBuild/dragon/releases/tag/1.7.2 Adds a CLI command (`r`/`release`) that when passed will #define `NDEBUG` and add anything in the `releaseflags:` DragonMake variable to the list of cflags. Otherwise, the value of `dbgflags:` will be added.

A future commit will add a `strip` flag to the CLI
